(source (official bin))
(config username "Matthew Ho")
(config project_name "Text Debugger")
(config npm_username "Matthew Ho")
(config github_username matthew-ho)
(config project_description "Text Debugger?")
(config package_manager Esy)
(config ci_cd Github)
(config syntax OCaml)
(config project_snake text_debugger)
(config project_slug text-debugger)
(config test_framework Alcotest)
